// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	profile "go-zero-pj/test/internal/handler/profile"
	user "go-zero-pj/test/internal/handler/user"
	"go-zero-pj/test/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/user/:name",
				Handler: user.GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/users/create",
				Handler: user.CreateUserHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/profile/:name",
				Handler: profile.GetProfileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/profile/create",
				Handler: profile.CreateProfileHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodHead,
				Path:    "/api/ping",
				Handler: PingHandler(serverCtx),
			},
		},
	)
}
