// Code generated by goctl. DO NOT EDIT.
package types

type User struct {
	Name string `json:"user"` // 用户姓名
}

type Student struct {
	Name string `json:"name"` // 学生姓名
}

type Teacher struct {
}

type Address struct {
	City string `json:"city"`
}

type InnerType struct {
	Image string `json:"image"`
}

type CreateRequest struct {
	InnerType
	Name    string    `form:"name"`
	Age     int       `form:"age,optional"`
	Address []Address `json:"address,optional"`
}

type GetRequest struct {
	Name string `path:"name"`
	Age  int    `form:"age,optional"`
}

type GetResponse struct {
	Code    int     `json:"code"`
	Desc    string  `json:"desc,omitempty"`
	Address Address `json:"address"`
	Service int     `json:"service"`
}
